import { Button } from '@/components/ui/button';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col items-center p-24">
        <nav className="flex justify-between w-full">
          <Button>
            <Link href="/">Fetch on render example</Link>
          </Button>
          <Button>
            <Link href="/ssr">SSR Example</Link>
          </Button>
          <Button>
            <Link href="/suspense">Suspense Example</Link>
          </Button>
        </nav>
        <main className="p-24 bg-slate-200 mt-12 w-9/12">{children}</main>
      </body>
    </html>
  );
}
